name: CI

on:
 push:
   branches:
     - master
 pull_request:
   branches:
     - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
          - 12
          - 14
          - 16
    name: node ${{ matrix.node_version }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm install

      - name: Build
        run: npm run build

      - name: Test and coverage
        run: npm run coverage

      - name: Check formatter
        run: npm run formatter

      - name: Check linter
        run: npm run lint

      - name: Check if dependencies up to date
        run: npm run checkDependencyUpdates
